### ISSUE TITLE
[maqz] Errored after: image-prebuildFiles

### ISSUE THREAD

**Issue by YuzuRyo61** [tamaina/old-tamaina.github.io#14]
Environment: Windows 10
Node.js Version: v11.10.1
![image](https://user-images.githubusercontent.com/18282413/54877271-7ac37400-4e5f-11e9-95a5-f3c2decd5dda.png)

※inkscapeはWindowsストアからインストールしています

**Comment by tamaina** [comment]
inkscapeはパスを通す必要があり、さらにストア版だとそれができないです…

（inkscapeでの圧縮自体最近追加した機能だから書いてなかった）

**Comment by tamaina** [comment]
そもそもパスを通す必要がないようにしますね

**Comment by tamaina** [comment]
（あっでもストア版がだめということには変わりない...）

**Comment by tamaina** [comment]
gulp-inkscapeパッケージの方でパスを通す必要がないように（`C:\Program Files\inkscape`があればそれが使うように）しました
